name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy on VPS
        run: |
          cd /var/www/portfolio
          ./deploy.sh
